[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
zircuit_testnet = "https://garfield-testnet.zircuit.com/"
flow_testnet = "https://testnet.evm.nodes.onflow.org"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
