[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
zircuit_testnet = "https://zircuit-mainnet.drpc.org"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
